spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

security:
  jwt:
    token:
      secretKey: pSBZhHgD1D8NP1U9UZgSeoOG0doMYpD+l7PnLfQpd4U=
      expireLength: 7200

email:
  sendgrid:
    apiKey: myapikey
    senderEmail: wooha34567@gmail.com
    base-url: https://api.sendgrid.com
    connect-timeout: 5000
    read-timeout: 30000
