spring:
  config:
    import: classpath:application-secrets-prod.yml

  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true

  sql:
    init:
      mode: embedded

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"

security:
  jwt:
    token:
      secretKey: ${security.jwt.token.secretKey}
      expireLength: ${security.jwt.token.expireLength}

email:
  sendgrid:
    apiKey: ${email.sendgrid.apiKey}
    senderEmail: ${email.sendgrid.senderEmail}
    base-url: https://api.sendgrid.com
    connect-timeout: 5000
    read-timeout: 30000
